# http://jd.bukkit.org/rb/apidocs/org/bukkit/Effect.html
# Usage: "effect name:permission.required"
# Do not include a permission to allow the effect for all players
effects:
- smoke:leap.smoke
- mobspawner flames:leap.flames
- ender signal:leap.ender
- potion break:leap.potion

# http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html
sounds:
- bat takeoff
- enderdragon wings
- shoot arrow

# The speed the player moves to where they are looking
velocity: 2.0

# Vertical velocity/push
elevation: 1.5