name: Leap
main: net.avicus.leap.Leap
version: 1.0
depend: [Avicus]
softdepend: [AntiCheat]
author: funkystudios
description: >
             LEAP! Double jump!
commands:
  trail:
    aliases: [trails]
    description: Modify your double jump trail
    usage: /trail (name)
    default: true